#!/bin/sh
export check_chrony=$(dpkg -l | grep "chrony" | awk '{print $2}')
export check_repository=$(ls /etc/apt/sources.list.d/ | awk '{print $1}')
export check_packet=$(ls /etc/apt/sources.list.d/ | awk '{print $1}' | cut -c 14-18)
export check_library=$(dpkg -l | grep "openstack" | awk '{print $2}')
export check_mariadb=$(dpkg -l | grep "mariadb" | awk '{print $2}')
export check_pymysql=$(dpkg -l | grep "pymysql" | awk '{print $2}')
export check_rabbitmq=$(dpkg -l | grep "rabbitmq" | awk '{print $2}')
export check_memcached=$(dpkg -l | grep "memcached" | awk '{print $2}')
export check_memcache=$(dpkg -l | grep "memcache" | awk '{print $2}')
export check_etcd=$(dpkg -l | grep "etcd" | awk '{print $2}')
export check_software=$(dpkg -l | grep "software-properties-common" | awk '{print $2}')
export check_keystone=$(dpkg -l | grep "keystone" | awk '{print $2} NR==2{exit}')
#export check_keystone=$(dpkg -l | grep "keystone" | awk '{print $2}')
export check_apache=$(dpkg -l | grep "apache" | awk '{print $2}')
export check_lib_apache=$(dpkg -l | grep "libapache2" | awk '{print $2}')
#export check_glance=$(dpkg -l | grep "glance" | awk '{print $2}')
export check_glance=$(dpkg -l | grep "glance" | awk '{print $2} NR==5{exit}')
export check_nova=$(dpkg -l | grep "nova" | awk '{print $2}')
#export check_nova=$(dpkg -l | grep "nova" | awk '{print $2}')
export check_nova=$(dpkg -l | grep "nova" | awk '{print $2} NR==7{exit}')
#export check_neutron=$(dpkg -l | grep "neutron" | awk '{print $2} NR==7{exit}')
export check_neutron_ops1=$(dpkg -l | grep "neutron" | awk '{print $2} NR==6{exit}')
export check_neutron_ops2=$(dpkg -l | grep "neutron" | awk '{print $2} NR==8{exit}')
export check_cinder=$(dpkg -l | grep "cinder" | awk '{print $2} NR==3{exit}')
export check_dashboard=$(dpkg -l | grep "openstack-dashboard" | awk '{print $2}')
#export check_neutron=$(dpkg -l | grep "neutron" | awk '{print $2}')
#export check_cinder=$(dpkg -l | grep "cinder" | awk '{print $2}')
